-- MySQL Script generated by MySQL Workbench
-- lun 17 jul 2023 17:01:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `modelo` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelo` DEFAULT CHARACTER SET utf8 ;
USE `modelo` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelo`.`usuario` ;

CREATE TABLE IF NOT EXISTS `modelo`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nick` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelo`.`direccion` ;

CREATE TABLE IF NOT EXISTS `modelo`.`direccion` (
  `idDireccion` INT NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `codPosta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDireccion`),
  CONSTRAINT `fk_direccion_usuario`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `modelo`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelo`.`coches` ;

CREATE TABLE IF NOT EXISTS `modelo`.`coches` (
  `matricula` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`matricula`, `idusuario`),
  INDEX `fk_coches_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_coches_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `modelo`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
