-- MySQL Script generated by MySQL Workbench
-- dom 01 ene 2023 16:31:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ejemplos` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ejemplos` DEFAULT CHARACTER SET utf8 ;
USE `ejemplos` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplos`.`usuario` ;

CREATE TABLE IF NOT EXISTS `ejemplos`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nick` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`datos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplos`.`datos` ;

CREATE TABLE IF NOT EXISTS `ejemplos`.`datos` (
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8mb4' NULL,
  `apellido_1` VARCHAR(45) CHARACTER SET 'utf8mb4' NULL,
  `apellido_2` VARCHAR(45) CHARACTER SET 'utf8mb4' NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_datos_usuario_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_datos_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `ejemplos`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplos`.`direccion` ;

CREATE TABLE IF NOT EXISTS `ejemplos`.`direccion` (
  `idusuario` INT NOT NULL,
  `calle` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_direccion_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_direccion_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `ejemplos`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

